[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = "https://ecom-project-tjkq.onrender.com"
  REACT_APP_SITE_URL = "https://gulkaar.netlify.app"
